### ISSUE TITLE
[question] What version of Carla does this work with?

### ISSUE THREAD

**Issue by josiahcoad** [jd730/CARLA-gym#1]

**Comment by jd730** [comment]
Hi @josiahcoad, I made it for CARLA 0.8.1 but unfortunately, since CARLA is changed a lot, it might not be compatible with the current version.

Maybe https://github.com/cjy1992/gym-carla would be helpful for you.

**Comment by josiahcoad** [comment]
@jd730 Thank you for the response! I thought (given your last commit) that it was for an older version. Thanks!
