### ISSUE TITLE
Could you please tell us what's the CARLA version?

### ISSUE THREAD

**Issue by zengsh-cqupt** [jd730/CARLA-gym#2]
Hi,
Could you please tell us what's the CARLA version?
Thanks

**Comment by jd730** [comment]
Hi @zengsh-cqupt, I made it for CARLA 0.8.1 but unfortunately, since CARLA is changed a lot, it might not be compatible with the current version.

Maybe https://github.com/cjy1992/gym-carla would be helpful for you.

**Comment by jd730** [comment]
Duplicated #1

**Comment by zengsh-cqupt** [comment]
> Duplicated #1

Sorry，I can‘t notice before.

**Comment by zengsh-cqupt** [comment]
> Hi @zengsh-cqupt, I made it for CARLA 0.8.1 but unfortunately, since CARLA is changed a lot, it might not be compatible with the current version.
> 
> Maybe https://github.com/cjy1992/gym-carla would be helpful for you.

Thank you so much.
